import os
import time
def startup():
    print("Welcome, this is Nature helper project")
    time.sleep(3)
    print("We will initialize an server for you, also the main site language is Russian")
    time.sleep(5)
    print("But it is settable in site itself")
    time.sleep(3)
    os.system("copy static/defs_sectime.py defs.py")
    print("This welcome text will not appear again")
    time.sleep(2)
    os.system("cls")
    print("Please wait, we are now starting.")
    time.sleep(1)
    os.system("cls")
    print("Please wait, we are now starting..")
    time.sleep(1)
    os.system("cls")
    print("Please wait, we are now starting...")
    time.sleep(1)
    os.system("cls")
